version: "3.9"

services:
    postgres:
        image: postgres:14
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - "4321:4321"
